'use client';
import {useState} from 'react';
import {Download} from 'lucide-react';
import {money,type Sale,type Movement,type Product} from '@/lib/model';
import {weekRange,validRange,summarize,margin,type DateRange} from '@/lib/reports';
export function DateRangePicker({range,onChange}:{range:DateRange;onChange:(range:DateRange)=>void}){
 return <section className="report-period" aria-label="Report date range"><div className="period-heading"><div><strong>Reporting period</strong><p>Inclusive dates · Europe/Zurich time</p></div><div className="period-presets"><button className="secondary" onClick={()=>onChange(weekRange())}>This week · Sun–Sat</button><button className="secondary" onClick={()=>onChange(weekRange(new Date(),true))}>Last week · Sun–Sat</button><button className="secondary" onClick={()=>onChange(weekRange(new Date(),false,true))}>Sun–Thu evenings</button></div></div><div className="period-dates"><label>From<input aria-label="Report start date" type="date" value={range.start} onChange={e=>onChange({...range,start:e.target.value})}/></label><span aria-hidden="true">→</span><label>To<input aria-label="Report end date" type="date" value={range.end} onChange={e=>onChange({...range,end:e.target.value})}/></label><p>Weekly exports include Friday and Saturday unless you choose a shorter range.</p></div>{!validRange(range)&&<p role="alert" className="amber">Choose both dates with the end on or after the start.</p>}</section>
}
export function Reports({sales,movements,range,onRange,onExport}:{sales:Sale[];movements:Movement[];range:DateRange;onRange:(range:DateRange)=>void;onExport:()=>void}){
 const r=summarize(sales,movements,range);const maxRevenue=Math.max(1,...r.days.map(d=>Math.abs(d.revenue)));const maxUnits=Math.max(1,...r.items.map(i=>Math.abs(i.units)));
 const profitMargin=r.profit===null||r.revenue<=0?null:r.profit/r.revenue*100;
 return <><DateRangePicker range={range} onChange={onRange}/><div className="view-actions"><p className="report-caption">This register’s purchases and stock deliveries in the selected period.</p><button className="secondary" disabled={!validRange(range)||!r.saleCount&&!r.voidCount} onClick={onExport}><Download size={17}/> Export purchases CSV</button></div>
 <div className="stat-row"><div><span>Net sales</span><strong>{money(r.revenue)}</strong><small>Charges less reversals</small></div><div><span>Cost of goods sold</span><strong>{r.missingCost?'Incomplete':money(r.cost)}</strong><small>{r.missingCost?`${money(r.cost)} recorded; costs missing`:'Purchase costs of items sold, less reversals'}</small></div><div><span>Gross profit</span><strong className={r.profit!==null&&r.profit<0?'amber':''}>{r.profit===null?'Unavailable':money(r.profit)}</strong><small>{profitMargin===null?'Needs complete sale costs and positive sales':`${profitMargin.toFixed(1)}% gross margin`}</small></div><div><span>Stock purchase expenses</span><strong>{money(r.deliverySpend)}</strong><small>{r.missingDeliveryCost?`${r.missingDeliveryCost} deliveries missing costs`:'Recorded delivery costs'}</small></div></div>
 {r.missingCost>0&&<div className="info-note">{r.missingCost} sold or reversed units have no cost snapshot. Gross profit is unavailable for this period. Set purchase costs in Inventory for future sales; existing receipts stay unchanged.</div>}
 <div className="analytics-grid"><section className="panel"><h2>Sales by day</h2><p>{r.saleCount} purchases · {r.voidCount} reversals · {r.units} net items</p>{r.days.length?<div className="daily-bars">{r.days.map(d=><div className="analytic-row" key={d.date}><div><span>{d.date}</span><strong>{money(d.revenue)}</strong></div><div className="bar-track"><div className={d.revenue<0?'bar negative':'bar'} style={{width:`${Math.abs(d.revenue)/maxRevenue*100}%`}}/></div></div>)}</div>:<div className="report-empty">No sales in this period. Try another date range or make a practice purchase.</div>}<div className="report-foot"><span>Average purchase</span><strong>{money(r.average)}</strong></div><small>Average uses original purchases; reversals appear separately.</small></section>
 <section className="panel"><h2>Popular items</h2><p>Ranked by net units sold, after reversals.</p>{r.items.length?r.items.slice(0,5).map((item,i)=><div className="analytic-row" key={item.id}><div><span>{i+1}. {item.name}</span><strong>{item.units} units</strong></div><div className="bar-track"><div className={item.units<0?'bar negative':'bar'} style={{width:`${Math.abs(item.units)/maxUnits*100}%`}}/></div></div>):<div className="report-empty">Your most popular items will appear after the first purchase.</div>}</section></div>
 <section className="panel report-table"><h2>Item performance</h2><p>Historical sale prices and purchase costs, including archived products.</p><div className="table-wrap"><table><thead><tr><th>Item</th><th>Net units</th><th>Net sales</th><th>Cost of goods</th><th>Gross profit</th><th>Margin</th></tr></thead><tbody>{r.items.map(i=><tr key={i.id}><td><strong>{i.name}</strong></td><td>{i.units}</td><td>{money(i.revenue)}</td><td>{i.missingCost?'Cost missing':money(i.cost)}</td><td>{i.missingCost?'—':money(i.revenue-i.cost)}</td><td>{i.missingCost||i.revenue<=0?'—':`${((i.revenue-i.cost)/i.revenue*100).toFixed(1)}%`}</td></tr>)}</tbody></table>{!r.items.length&&<div className="report-empty">No item sales in this period.</div>}</div></section>
 <div className="info-note">Gross profit is net sales minus the recorded purchase cost of items sold. Stock purchase expenses show deliveries received in this period and are not deducted again from gross profit. Other operating expenses and taxes are not tracked. Reversals are counted on the date they were recorded.</div></>
}

export function PriceFields({product}:{product:Product|null}){
 const [price,setPrice]=useState(String((product?.price_cents??0)/100));const [cost,setCost]=useState(product?.cost_cents===undefined?'':String(product.cost_cents/100));
 const p=Math.round(Number(price)*100),c=cost.trim()===''?undefined:Math.round(Number(cost)*100);const valid=price!==''&&Number.isSafeInteger(p)&&p>=0&&(c===undefined||Number.isSafeInteger(c)&&c>=0);const percent=valid?margin(p,c):null;
 return <><div className="form-row"><label>Sale price (CHF)<input name="price" type="number" min="0" step="0.01" required value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Purchase cost / unit (CHF)<input name="cost" type="number" min="0" step="0.01" placeholder="Not set" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><div className="info-note" aria-live="polite">{!valid?'Enter non-negative prices.':c===undefined?'Add a purchase cost to calculate profit and margin.':`Profit per item: ${money(p-c)} · Margin: ${percent===null?'not applicable at zero sale price':percent.toFixed(1)+'%'}`}</div></>
}
