import Dexie, {type Table} from 'dexie';
import {uuid,makeLines,stockFor,type Product,type Student,type Operator,type Shift,type Sale,type Movement,type Event,type Count} from './model';
class StoreDB extends Dexie {
 products!:Table<Product,string>;students!:Table<Student,string>;operators!:Table<Operator,string>;shifts!:Table<Shift,string>;sales!:Table<Sale,string>;movements!:Table<Movement,string>;outbox!:Table<Event,string>;counts!:Table<Count,string>;settings!:Table<{key:string;value:string},string>;
 constructor(){super('las-savoy-practice-v1');this.version(1).stores({products:'id,category',students:'id,student_number,card_uid_hash',operators:'id',shifts:'id,operator_id',sales:'id,student_id,original_transaction_id,occurred_at',movements:'id,product_id,transaction_id',outbox:'id,status',counts:'id',settings:'key'})}
}
export const db=new StoreDB();
export async function hashPin(pin:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:120000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits),v=>v.toString(16).padStart(2,'0')).join('')}
export async function verifyPin(op:Operator,pin:string){return op.pin_hash===await hashPin(pin,op.pin_salt)}
export async function hashCard(uid:string){let s=await db.settings.get('card-salt');if(!s){s={key:'card-salt',value:uuid()};await db.settings.put(s)}const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(s.value),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(uid.trim().toUpperCase().replace(/[\s:-]/g,'')))),v=>v.toString(16).padStart(2,'0')).join('')}
const event=(kind:Event['kind'],payload:unknown,actor_id:string):Event=>({id:uuid(),kind,payload,actor_id,occurred_at:new Date().toISOString(),status:'pending'});
export async function seed(){if(await db.settings.get('seeded'))return;
 const definitions=[['Paprika crisps','Snacks',250,'🥔',24],['Milk chocolate','Snacks',200,'🍫',32],['Oreo cookies','Snacks',250,'🍪',18],['Gummy bears','Snacks',200,'🍬',4],['Still water','Drinks',150,'💧',36],['Ice tea · Peach','Drinks',250,'🧃',22],['Coca-Cola','Drinks',250,'🥤',16],['Apple juice','Drinks',200,'🍎',3],['Instant noodles','Snacks',300,'🍜',12],['Toothbrush','Toiletries',350,'🪥',8],['Toothpaste','Toiletries',400,'🧴',6],['Notebook','Supplies',300,'📓',10]] as const;
 const products=definitions.map((d,i)=>({id:uuid(),name:d[0],category:d[1],price_cents:d[2],image_url:d[3],sort_order:i,active:true,low_stock_threshold:5}));
 const ops=await Promise.all([['Alex Morgan','staff','1234'],['Sam Taylor','prefect','1111']].map(async([name,role,pin])=>{const pin_salt=uuid();return{id:uuid(),name,role:role as Operator['role'],pin_salt,pin_hash:await hashPin(pin,pin_salt)}}));
 const students=[['Avery','Chen','DEMO-001'],['Jordan','Martin','DEMO-002'],['Riley','Patel','DEMO-003'],['Casey','Dubois','DEMO-004']].map(([first_name,last_name,student_number])=>({id:uuid(),first_name,last_name,student_number,dorm:'Savoy',active:true}));
 await db.transaction('rw',[db.products,db.operators,db.students,db.movements,db.settings],async()=>{if(await db.settings.get('seeded'))return;await db.products.bulkAdd(products);await db.operators.bulkAdd(ops);await db.students.bulkAdd(students);await db.movements.bulkAdd(products.map((p,i)=>({id:uuid(),product_id:p.id,quantity_delta:definitions[i][4],movement_type:'delivery' as const,operator_id:ops[0].id,note:'Practice opening stock',occurred_at:new Date().toISOString()})));await db.settings.put({key:'seeded',value:'true'})})
}
export async function startShift(op:Operator){const shift:Shift={id:uuid(),operator_id:op.id,operator_name:op.name,role:op.role,opened_at:new Date().toISOString()};await db.transaction('rw',[db.shifts,db.outbox],async()=>{if((await db.shifts.toArray()).some(s=>!s.closed_at))throw Error('Close the previous shift before opening another.');await db.shifts.add(shift);await db.outbox.add(event('shift',shift,op.id))});return shift}
export async function closeShift(shift:Shift,closed_at=new Date().toISOString()){if(new Date(closed_at)<new Date(shift.opened_at)||new Date(closed_at)>new Date())throw Error('Choose an end time between shift start and now.');const next={...shift,closed_at};await db.transaction('rw',[db.shifts,db.outbox],async()=>{await db.shifts.put(next);await db.outbox.add(event('shift',next,shift.operator_id))})}
export async function checkout(student:Student,shift:Shift,cart:Record<string,number>,saleId=uuid()){
 return db.transaction('rw',[db.products,db.students,db.shifts,db.sales,db.movements,db.outbox],async()=>{
 const prior=await db.sales.get(saleId);if(prior)return prior;
 if((await db.shifts.get(shift.id))?.closed_at)throw Error('This shift is closed.');
 if(!(await db.students.get(student.id))?.active)throw Error('Student is not active.');
 const items=makeLines(cart,await db.products.toArray());if(!items.length)throw Error('Add an item first.');const total_cents=items.reduce((n,i)=>n+i.line_total_cents,0);
 const sale:Sale={id:saleId,student_id:student.id,student_number:student.student_number,student_name:`${student.first_name} ${student.last_name}`,shift_id:shift.id,operator_id:shift.operator_id,operator_name:shift.operator_name,total_cents,occurred_at:new Date().toISOString(),is_void:false,items};
 await db.sales.add(sale);await db.movements.bulkAdd(items.map(i=>({id:uuid(),product_id:i.product_id,quantity_delta:-i.quantity,movement_type:'sale' as const,transaction_id:sale.id,operator_id:shift.operator_id,note:'',occurred_at:sale.occurred_at})));await db.outbox.add(event('sale',sale,shift.operator_id));return sale})
}
export async function voidSale(original:Sale,staff:Operator,shift:Shift,note:string){if(staff.role!=='staff'||!note.trim())throw Error('Staff authorization and a reason are required.');return db.transaction('rw',[db.sales,db.movements,db.outbox],async()=>{if(original.is_void||await db.sales.where('original_transaction_id').equals(original.id).count())throw Error('This transaction is already voided.');const sale:Sale={...original,id:uuid(),operator_id:staff.id,operator_name:staff.name,shift_id:shift.id,total_cents:-original.total_cents,occurred_at:new Date().toISOString(),is_void:true,original_transaction_id:original.id,note};await db.sales.add(sale);await db.movements.bulkAdd(sale.items.map(i=>({id:uuid(),product_id:i.product_id,quantity_delta:i.quantity,movement_type:'void' as const,transaction_id:sale.id,operator_id:staff.id,note,occurred_at:sale.occurred_at})));await db.outbox.add(event('void',sale,staff.id))})}
export async function saveProduct(product:Product,op:Operator){if(op.role!=='staff')throw Error('Staff only.');await db.transaction('rw',[db.products,db.outbox],async()=>{await db.products.put(product);await db.outbox.add(event('product',product,op.id))})}
export async function saveStudent(student:Student,op:Operator){await db.transaction('rw',[db.students,db.outbox],async()=>{await db.students.put(student);await db.outbox.add(event('student',student,op.id))})}
export async function receive(product_id:string,quantity:number,note:string,op:Operator){if(op.role!=='staff'||!Number.isSafeInteger(quantity)||quantity<=0)throw Error('Enter a positive whole quantity.');const movement:Movement={id:uuid(),product_id,quantity_delta:quantity,movement_type:'delivery',operator_id:op.id,note,occurred_at:new Date().toISOString()};await db.transaction('rw',[db.movements,db.outbox],async()=>{await db.movements.add(movement);await db.outbox.add(event('delivery',movement,op.id))})}
export async function saveCount(values:Record<string,string>,op:Operator){if(op.role!=='staff')throw Error('Staff only.');await db.transaction('rw',[db.movements,db.counts,db.outbox],async()=>{const movements=await db.movements.toArray();const lines=Object.entries(values).filter(([,v])=>v!=='').map(([product_id,v])=>{const counted_qty=Number(v);if(!Number.isSafeInteger(counted_qty)||counted_qty<0)throw Error('Counts must be non-negative whole numbers.');return{product_id,expected_qty:stockFor(product_id,movements),counted_qty}});if(!lines.length)throw Error('Enter at least one count.');const count:Count={id:uuid(),operator_id:op.id,occurred_at:new Date().toISOString(),lines};await db.counts.add(count);await db.movements.bulkAdd(lines.map(l=>({id:uuid(),product_id:l.product_id,quantity_delta:l.counted_qty-l.expected_qty,movement_type:'count_correction' as const,operator_id:op.id,note:`Count ${count.id}`,occurred_at:count.occurred_at})));await db.outbox.add(event('count',count,op.id))})}
